[package]
name = "hcid_js"
version = "0.0.7"
license = "Apache-2.0"

[lib]
name = "hcid_js"
crate-type = ["cdylib"]

[dependencies]
hcid = { path = "../../hcid" }
wasm-bindgen = "=0.2.40"
wee_alloc = "=0.4.4"
